pipelines:
  branches:
    master:
      - step:
          script:
            - apt-get update && apt-get install -y unzip git
            - git push https://$USERNAME:$PASSWORD@github.com/mediaopt/worldline-shopware-6.git
            - git push https://$USERNAME:$PASSWORD@github.com/mediaopt/worldline-shopware-6.git --tags
    main_65: 
      - step:
          script:
            - apt-get update && apt-get install -y unzip git
            - git push https://$USERNAME:$PASSWORD@github.com/mediaopt/worldline-shopware-6.git
            - git push https://$USERNAME:$PASSWORD@github.com/mediaopt/worldline-shopware-6.git --tags  
        