pipelines:
  branches:
    master:
      - step:
          script:
            - apt-get update && apt-get install -y unzip git
            - git push https://$USERNAME:$PASSWORD@github.com/mediaopt/moptworldline.git
            - git push https://$USERNAME:$PASSWORD@github.com/mediaopt/dhl-oxid-hub.git --tags
            